FROM node:22-alpine

WORKDIR /app

# Копируем файлы зависимостей
COPY package*.json ./
RUN npm install

# Копируем весь остальной код фронтенда
COPY . .

EXPOSE 5173

# Запускаем сервер Vite с флагом --host
CMD ["npm", "run", "dev", "--", "--host"]